package com.aissue.test.pdf;

import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import org.xhtmlrenderer.pdf.ITextFontResolver;
import org.xhtmlrenderer.pdf.ITextRenderer;

import java.io.*;

public class testPDF {

    private static final String DEST = "D:/HelloWorld_CN_HTML.pdf";
    private static final String HTML = "d:/iText.htm";
    private static final String FONT = "simhei.ttf";

    public static void main(String[] args) throws Exception{
//        hz();
        html();
    }

    public static void hz() throws Exception{
        Document document = new Document();
        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(DEST));
        document.open();
        Font f1 = FontFactory.getFont(FONT, BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);
        document.add(new Paragraph("hello world,我是鲁家宁", f1));
        document.close();
        writer.close();
    }
    public static void html() throws Exception{
        StringBuffer sb = new StringBuffer();
        PrintStream printStream = new PrintStream(new FileOutputStream("d:/iText.html"));
        sb.append("<html>");
        sb.append("<head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>");
        sb.append("<style>body{font-family:SimHei;}</style></head>");
        sb.append("<body>");
        sb.append("<div>");
        sb.append("<h1 align=\"center\">XXX</h1>");
        sb.append("<table border=\"1\" cellspacing=\"0\" width=\"100%\">");
        sb.append("<tr>");
        sb.append("<td width=\"30%\" align=\"center\" bgcolor=\"#dedede\">身份证号码</td>");
        sb.append("<td width=\"10%\" align=\"center\" bgcolor=\"#dedede\">性别</td>");
        sb.append("<td width=\"10%\" align=\"center\" bgcolor=\"#dedede\">民族</td>");
        sb.append("<td width=\"30%\" align=\"center\" bgcolor=\"#dedede\">户籍地</td>");
        sb.append("<td width=\"20%\" align=\"center\" bgcolor=\"#dedede\">政治面貌</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td align=\"center\">Text 2A</td>");
        sb.append("<td align=\"center\">Text 2B</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("<td align=\"center\">Text 1C</td>");
        sb.append("</tr>");
        sb.append("</table>");
        sb.append("<br/>");
        sb.append(">>>社会基础信息");
        sb.append("<table border=\"1\" cellspacing=\"0\" width=\"100%\">");
        sb.append("<tr>");
        sb.append("<td width=\"15%\" align=\"center\" bgcolor=\"#dedede\">姓名</td>");
        sb.append("<td width=\"20%\" align=\"center\">姓名</td>");
        sb.append("<td width=\"10%\" align=\"center\" bgcolor=\"#dedede\">曾用名</td>");
        sb.append("<td width=\"15%\" align=\"center\">曾用名</td>");
        sb.append("<td width=\"15%\" align=\"center\" bgcolor=\"#dedede\">民族</td>");
        sb.append("<td width=\"20%\" align=\"center\">民族</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td align=\"center\" bgcolor=\"#dedede\">身份证号码</td>");
        sb.append("<td align=\"center\">身份证号码</td>");
        sb.append("<td align=\"center\" bgcolor=\"#dedede\">性别</td>");
        sb.append("<td align=\"center\">性别</td>");
        sb.append("<td align=\"center\" bgcolor=\"#dedede\">年龄</td>");
        sb.append("<td align=\"center\">年龄</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td align=\"center\" bgcolor=\"#dedede\">出生日期</td>");
        sb.append("<td align=\"center\">出生日期</td>");
        sb.append("<td align=\"center\" bgcolor=\"#dedede\">出生地</td>");
        sb.append("<td align=\"center\">出生地</td>");
        sb.append("<td align=\"center\" bgcolor=\"#dedede\">籍贯</td>");
        sb.append("<td align=\"center\">籍贯</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td align=\"center\" bgcolor=\"#dedede\">文化程度</td>");
        sb.append("<td align=\"center\">文化程度</td>");
        sb.append("<td align=\"center\" bgcolor=\"#dedede\">婚姻状况</td>");
        sb.append("<td align=\"center\">婚姻状况</td>");
        sb.append("<td align=\"center\" bgcolor=\"#dedede\">身高</td>");
        sb.append("<td align=\"center\">身高</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td align=\"center\" bgcolor=\"#dedede\">工作单位</td>");
        sb.append("<td align=\"center\" colspan=\"5\">工作单位</td>");
        sb.append("</tr>");
        sb.append("</table>");
        sb.append("<br/>");
        sb.append(">>>家庭基础信息");
        sb.append("<table border=\"1\" cellspacing=\"0\" width=\"100%\">");
        sb.append("<tr>");
        sb.append("<td  align=\"center\" bgcolor=\"#dedede\">关系</td>");
        sb.append("<td  align=\"center\" bgcolor=\"#dedede\">姓名</td>");
        sb.append("<td  align=\"center\" bgcolor=\"#dedede\">性别</td>");
        sb.append("<td  align=\"center\" bgcolor=\"#dedede\">身份证号码</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td align=\"center\">父子</td>");
        sb.append("<td align=\"center\">Text 2B</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td align=\"center\">母子</td>");
        sb.append("<td align=\"center\">Text 2B</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td align=\"center\">T配偶</td>");
        sb.append("<td align=\"center\">Text 2B</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td align=\"center\">第一监护人</td>");
        sb.append("<td align=\"center\">Text 2B</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td align=\"center\">第二监护人</td>");
        sb.append("<td align=\"center\">Text 2B</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("<td align=\"center\">Text 2C</td>");
        sb.append("</tr>");
        sb.append("</table>");
        sb.append("<br/>");
        sb.append(">>>房产基本信息");
        sb.append("<table border=\"1\" cellspacing=\"0\" width=\"100%\">");
        sb.append("<th colspan=\"4\" align=\"left\">房产记录1:</th>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">不动产权证号</td>");
        sb.append("<td  align=\"center\" colspan=\"3\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td  align=\"center\" bgcolor=\"#dedede\">房屋坐落</td>");
        sb.append("<td  align=\"center\" colspan=\"3\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">房屋所有权人</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">建筑层数</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">建筑面积</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">套内面积</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">所有权登记时间</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">房屋状态</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">登记机构</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">房屋性质</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">共有情况</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\"></td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("</table>");
        sb.append("<br/>");
        sb.append(">>>车辆基本信息");
        sb.append("<table border=\"1\" cellspacing=\"0\" width=\"100%\">");
        sb.append("<th colspan=\"4\" align=\"left\">车辆记录1:</th>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">车辆类型</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">车辆型号</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">车辆颜色</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">使用性质</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">车牌号码</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">号牌种类</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">机动车所有人</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">初次登记时间</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">注销时间</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\"></td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("</table>");
        sb.append("<br/>");
        sb.append(">>>房产交易信息");
        sb.append("<table border=\"1\" cellspacing=\"0\" width=\"100%\">");
        sb.append("<th colspan=\"4\" align=\"left\">交易记录1:</th>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">交易时间</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">交易方类型</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">纳税人姓名</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">建筑面积</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">经济机构</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">房产交易序号</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">合同编号</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">合同ID</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">交易价格</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">合同备案时间</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">全省统一房屋编号</td>");
        sb.append("<td width=\"25%\" align=\"center\" colspan=\"3\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">房屋地址</td>");
        sb.append("<td width=\"25%\" align=\"center\" colspan=\"3\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">姓名</td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">证件类型</td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">证件号码</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">转让方</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">受让方</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("</table>");
        sb.append("<br/>");
        sb.append(">>>社保基础信息");
        sb.append("<table border=\"1\" cellspacing=\"0\" width=\"100%\">");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">社保姓名</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">社保号码</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">退休状态</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">参保地区</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\">参加工作时间</td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("<td width=\"25%\" align=\"center\" bgcolor=\"#dedede\"></td>");
        sb.append("<td width=\"25%\" align=\"center\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"20%\" align=\"center\" bgcolor=\"#dedede\">保险种类</td>");
        sb.append("<td width=\"20%\" align=\"center\" bgcolor=\"#dedede\">缴费状态</td>");
        sb.append("<td width=\"60%\" align=\"center\" bgcolor=\"#dedede\" colspan=\"2\">参保单位</td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"20%\" align=\"center\">养老保险</td>");
        sb.append("<td width=\"20%\" align=\"center\"></td>");
        sb.append("<td width=\"60%\" align=\"center\" colspan=\"2\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"20%\" align=\"center\">医疗保险</td>");
        sb.append("<td width=\"20%\" align=\"center\"></td>");
        sb.append("<td width=\"60%\" align=\"center\" colspan=\"2\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"20%\" align=\"center\">生育保险</td>");
        sb.append("<td width=\"20%\" align=\"center\"></td>");
        sb.append("<td width=\"60%\" align=\"center\" colspan=\"2\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"20%\" align=\"center\">工伤保险</td>");
        sb.append("<td width=\"20%\" align=\"center\"></td>");
        sb.append("<td width=\"60%\" align=\"center\" colspan=\"2\"></td>");
        sb.append("</tr>");
        sb.append("<tr>");
        sb.append("<td width=\"20%\" align=\"center\">失业宝箱</td>");
        sb.append("<td width=\"20%\" align=\"center\"></td>");
        sb.append("<td width=\"60%\" align=\"center\" colspan=\"2\"></td>");
        sb.append("</tr>");
        sb.append("</table>");
        sb.append("</div>");
        sb.append("</body>");
        sb.append("</html>");
        printStream.println(sb.toString());

        printStream.flush();

        ITextRenderer render = new ITextRenderer();
        ITextFontResolver fontResolver = render.getFontResolver();
        fontResolver.addFont(FONT, BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);
        // 解析html生成pdf
        render.setDocumentFromString(sb.toString());
        //解决图片相对路径的问题
        render.getSharedContext().setBaseURL(null);
        render.layout();
        render.createPDF(new FileOutputStream(DEST));

        /*// step 1
        Document document = new Document();
        // step 2
        PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(DEST));
        // step 3
        document.open();
        // step 4
        XMLWorkerFontProvider fontImp = new XMLWorkerFontProvider(XMLWorkerFontProvider.DONTLOOKFORFONTS);
        fontImp.register(FONT);
        XMLWorkerHelper.getInstance().parseXHtml(writer, document,
                new FileInputStream("d:/iText.html"), null, Charset.forName("UTF-8"), fontImp);
        // step 5
        document.close();*/
    }
}
